# Generated by Django 2.2 on 2019-06-22 11:53

from django.db import migrations, models
import sorl.thumbnail.fields
import streams.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rtmp_url', models.CharField(default='rtmp://62.210.116.81:1935/show', max_length=255)),
                ('url', models.CharField(default='rtmp://62.210.116.81:1935/show<function id_generator at 0x107e1e950>', max_length=255)),
                ('key', models.CharField(default=streams.models.id_generator, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='media/stream_cover')),
                ('status', models.BooleanField(blank=True, choices=[(True, 'Start'), (False, 'Stop')], null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_info', models.DateTimeField(blank=True, default=streams.models.calculate_expiry_time, null=True)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=None, to='streams.LiveStream')),
            ],
        ),
    ]
