# Generated by Django 2.2 on 2019-06-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_subscriptions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='url',
        ),
    ]
