# Generated by Django 2.2 on 2019-05-30 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_auto_20190530_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Start'), (False, 'Stop')], null=True),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, null=True),
        ),
    ]
