# Generated by Django 2.2 on 2019-06-07 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0003_auto_20190530_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
                ('uid', models.ForeignKey(blank=True, null=True, on_delete=None, to='streams.LiveStream')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
