# Generated by Django 2.2 on 2019-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='sub_info',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
